version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    directory: "pkg/mdx"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
