/*
 * Code generated by maegi. DO NOT EDIT.
 */

export const category = { something: { main: "#ff00ff" } } as const;

export const gray = {
  "50": "#f8f8f8",
  "100": "#e3e3e3",
  "200": "#c7c7c7",
  "300": "#ababab",
  "400": "#919191",
  "500": "#777777",
  "600": "#5e5e5e",
  "700": "#464646",
  "800": "#303030",
  "900": "#1b1b1b",
} as const;

export const green = {
  "50": "#f0fcf6",
  "100": "#d1f6e4",
  "200": "#a0dbc1",
  "300": "#61c19f",
  "400": "#38a585",
  "500": "#1b896b",
  "600": "#0d6d54",
  "700": "#00533e",
  "800": "#003a2c",
  "900": "#00231b",
} as const;

export const primary = { main: "#38a585" } as const;

export const text = { main: "#000000c9", light: "#00000066" } as const;
