#!/usr/bin/env bash
set -euo pipefail

cd pkg

git tag --points-at HEAD | while read tag; do
  re="^v(.+)$"
  if [[ $tag =~ $re ]]; then
    VERSION=${BASH_REMATCH[1]}
    echo Publish ${VERSION}

    for PACKAGE in *; do

      cat "$PACKAGE/package.json" | jq --arg version "$VERSION" '.version = $version' > tmp;
      mv tmp "$PACKAGE/package.json"

      pushd "$PACKAGE"; npm publish . --access public; popd
    done
  fi
done
