#!/usr/bin/env bash
set -euo pipefail

cd packages

git tag --points-at HEAD | while read tag; do
  re="^v(.+)$"
  if [[ $tag =~ $re ]]; then
    VERSION=${BASH_REMATCH[1]}
    echo Publish ${VERSION}

    for PACKAGE in *; do

      cat "$PACKAGE/package.json" | jq --arg version "$VERSION" '.version = $version' > tmp;
      mv tmp "$PACKAGE/package.json"

      npm publish "$PACKAGE" --access public
    done
  fi
done
