name: Dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: gh pr review --approve "$PULL_REQUEST_URL"
        env:
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - if: ${{ steps.metadata.outputs.directory == '/' }}
        run: gh pr merge --auto --squash "$PULL_REQUEST_URL"
        env:
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
