name: ESLint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - run: nix run github:nicknovitski/nix-develop .#workflow

      - run: eslint .
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint.sarif
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        continue-on-error: true

      - uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
        with:
          sarif_file: eslint.sarif
          wait-for-processing: true
