name: Niquis
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  niquis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      - run: nix run .#nix-develop .#workflow
      - run: pnpm install

      - run: npm run build

      - uses: niquis/action@ebea86af751e3807ab59167a16b15b4629739214 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIQUIS_TOKEN: ${{ secrets.NIQUIS_TOKEN }}
