name: Pull Request Verification

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  integrity:
    if: github.event.pull_request.draft == false
    name: Integrity
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run .#nix-develop .#workflow

      - run: npm run build

      - id: create-pull-request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "Fix integrity violations in #${{ github.event.pull_request.number }}"
          branch: fix-integrity-violations-${{ github.event.pull_request.number }}
          base: ${{ github.event.pull_request.head.ref }}

      - if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        run: exit 1

  biome:
    if: github.event.pull_request.draft == false
    name: Biome
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run .#nix-develop .#workflow

      - run: biome check --reporter=github .

  knip:
    if: github.event.pull_request.draft == false
    name: Knip
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run .#nix-develop .#workflow

      - run: pnpx knip
        working-directory: pkg/macro

      - run: pnpx knip
        working-directory: pkg/mdx

      - run: pnpx knip
        working-directory: pkg/timvir
