name: Update Browserslist Database

on:
  workflow_dispatch: {}
  schedule:
    - cron: "41 8 * * *"

jobs:
  update-browserslist-database:
    name: Update Browserslist Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - run: nix run github:nicknovitski/nix-develop .#workflow

      - run: pnpm up caniuse-lite
      - run: pnpm dedupe

      - uses: peter-evans/create-pull-request@v7
        with:
          branch: update-browserslist-database
          title: Update Browserslist Database
          commit-message: Update Browserslist Database
