name: Urnerys

on: deployment_status

env:
  URNERYS: app.urnerys.dev
  BUILD: "github-run-${{ github.run_id }}-${{ github.run_attempt }}"

permissions:
  contents: read

jobs:
  urnerys:
    name: Urnerys
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run .#nix-develop .#workflow
      - run: pnpm install
      - run: ./node_modules/.bin/playwright install --with-deps chromium webkit

      - run: |
          curl -sf -X POST -H "Content-Type: application/json" -d '{ "id": "'"$BUILD"'", "build": { "origin": { "commit": "${{ github.sha }}" } } }' "https://$URNERYS/api/v1/projects/timvir/builds"

      - run: ./node_modules/.bin/playwright test --retries 3 ./urnerys/*.spec.ts
        env:
          URL: ${{ github.event.deployment_status.target_url }}

      - run: |
          case "${{ github.event.deployment_status.environment }}" in
            Production)
              curl -sf -X PATCH -H "Content-Type: application/json" -d '{ "baseline": { "build": "'"$BUILD"'" } }' "https://$URNERYS/api/v1/projects/timvir/baselines/production"
              ;;
            *)
              curl -sf -X POST -H "Content-Type: application/json" -d '{ "check": { "baseline": "production" } }' "https://$URNERYS/api/v1/projects/timvir/builds/$BUILD/checks"
              ;;
          esac
